source 'https://rubygems.org'

gem 'puma'
gem 'rack'
gem 'sinatra'
gem 'typhoeus'
gem 'activemodel', '~> 5.0', '>= 5.0.0.1'
gem 'elasticsearch-api'

group :development, :test do
  gem 'pry-meta'
  gem 'sinatra-reloader'
end

group :test do
  gem 'vcr'
  gem 'simplecov', require: false
  gem 'rspec'
end
